import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {createServer} from 'node:net';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {todayInIndia} from '../workflow.js';
const fixedKey=Buffer.alloc(32,11).toString('base64');
test('career MVP gates consent/approval, persists profile and pipeline, exports and deletes fictional data',{timeout:45000},async()=>{
 const temp=mkdtempSync(join(tmpdir(),'career-api-test-'));const socket=createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));const base='http://localhost:'+port;let child,cookie;
 const start=async()=>{child=spawn(process.execPath,['server.js'],{windowsHide:true,env:{...process.env,PORT:String(port),APP_URL:base,CAREER_DATA_KEY:fixedKey,CAREER_STORE_PATH:join(temp,'vault'),DECISION_STORE_PATH:join(temp,'decisions'),SMTP_HOST:'',HTTPS_CERT_FILE:'',HTTPS_KEY_FILE:''},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Server did not start')),10000);child.stdout.once('data',()=>{clearTimeout(timeout);resolve();});child.once('exit',()=>{clearTimeout(timeout);reject(new Error('Server exited'));});});};
 const stop=async()=>{if(child&&child.exitCode===null){const done=once(child,'exit');child.kill();await done;}};
 const call=async(path,data,extra={})=>{const response=await fetch(base+path,{method:data===undefined?'GET':'POST',headers:{Cookie:cookie||'',Origin:base,'Content-Type':'application/json',...extra},body:data===undefined?undefined:typeof data==='string'?data:JSON.stringify(data)});if(response.headers.getSetCookie().length)cookie=response.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');return response;};
 try{await start();let state=await(await call('/api/career/state')).json();assert.equal(state.consent,false);assert.equal((await call('/api/resume','Fictional Candidate with SQL banking experience.',{'X-File-Name':'fictional.txt'})).status,400);assert.equal((await call('/api/career/consent',{agree:true})).status,200);assert.equal((await call('/api/resume','Fictional Candidate\ntest@example.com\nSUMMARY\nSenior banking analyst with SQL and UAT.\nEDUCATION\nDegree',{'X-File-Name':'fictional.txt'})).status,200);
 state=await(await call('/api/career/state')).json();assert.equal(state.profile.confirmed,false);const profile={...state.profile,totalYears:12,confirmed:true,skills:[{name:'SQL',status:'Proficient',finish:''},{name:'UAT',status:'Proficient',finish:''}],certifications:[],education:['Degree'],roles:[{title:'Senior Analyst',employer:'Fictional employer',client:'Fictional client',start:'2020-01',end:'2026-01',bullets:['Reduced defects by 20%.']}],preferences:{locations:[{city:'Pune',country:'India'}]}};
 assert.equal((await call('/api/career/profile',{profile})).status,200);state=await(await call('/api/career/state')).json();assert.equal(state.roleGroups.length,3);assert.equal(state.history.length,1);
 const vacancy={title:'Senior Analyst',company:'Fictional Bank',source:'Test',location:'Pune',country:'India',posted:todayInIndia(),applicationOpen:true,description:'SQL UAT banking and stakeholder management required. Minimum 10 years experience.',applyLink:'https://example.com/vacancy'};assert.equal((await call('/api/jobs',[vacancy])).status,200);state=await(await call('/api/career/state')).json();const key=state.jobs[0].key;assert.ok(state.results[0].scoreParts);assert.equal((await call('/api/career/gmail',{address:'fictional@example.com',appPassword:'abcdefghijklmnop',save:true})).status,200);assert.ok(!(await(await call('/api/career/state')).text()).includes('abcdefghijklmnop'));assert.ok(!(await(await call('/api/career/export')).text()).includes('abcdefghijklmnop'));
 const draft=await(await call('/api/career/tailor',{key})).json();assert.equal(draft.claims.length,0);assert.equal((await call('/api/career/resume?id='+draft.id+'&format=docx')).status,400);assert.equal((await call('/api/career/approve',{id:draft.id,approve:false})).status,400);const approval=await(await call('/api/career/approve',{id:draft.id,approve:true})).json();assert.equal(approval.url,vacancy.applyLink);assert.match(approval.message,/nothing has been sent/);const pdf=await call('/api/career/resume?id='+draft.id+'&format=pdf');assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');assert.equal((await call('/api/career/stage',{key,stage:'Saved'})).status,200);assert.equal((await call('/api/career/stage',{key,stage:'Applied'})).status,200);assert.match(await(await call('/api/career/pipeline-export')).text(),/Fictional Bank/);
 await stop();await start();state=await(await call('/api/career/state')).json();assert.equal(state.profile.name,'Fictional Candidate');assert.equal(state.pipeline[0].stage,'Applied');assert.equal(state.pipeline[0].history.length,2);assert.equal((await call('/api/career/consent',{agree:true},{Origin:'https://evil.example'})).status,403);assert.equal((await call('/api/career/delete',{confirm:'no'})).status,400);assert.equal((await call('/api/career/delete',{confirm:'DELETE'})).status,200);state=await(await call('/api/career/state')).json();assert.equal(state.profile,null);assert.equal(state.pipeline.length,0);assert.equal(state.consent,false);
 }finally{await stop();rmSync(temp,{recursive:true,force:true});}
});
