import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

test('Submit applies each minimum, selection waits for Submit, and Refresh retrieves the feed', async () => {
  const elements = new Map();
  const element = selector => {
    if (!elements.has(selector)) elements.set(selector, { value: selector === '#threshold' ? '75' : selector === '#record-limit' ? '5' : '', textContent: '', innerHTML: '', hidden: false, addEventListener() {}, scrollIntoView() {} });
    return elements.get(selector);
  };
  let feedRequests = 0;
  let cleared = false;
  let decisionRequests = 0;
  const jobs = [25, 50, 75, 100].map(score => ({ id: String(score), score, title: 'Role', company: 'Company', location: 'Pune', country: 'India', candidateSkills: ['SQL'], required: ['SQL'], matched: ['SQL'], gaps: [], recommendedAction: 'Review', interview: [] }));
  const context = vm.createContext({
    document: { documentElement: { dataset: {} }, querySelector: element, querySelectorAll: () => [] }, URL,
    fetch: async path => {
      if (path === '/api/feed') feedRequests++;
      if (path === '/api/clear') cleared = true;
      if (path === '/api/decision') decisionRequests++;
      return { ok: true, json: async () => path.startsWith('/api/state') ? { resumeReady: !cleared, resumeName: cleared ? '' : 'resume.txt', jobs: cleared ? [] : jobs, feedConfigured: true, jobSources: { linkedin: true, naukri: false } } : { ok: true } };
    }
  });
  vm.runInContext(readFileSync(new URL('../public/app.js', import.meta.url), 'utf8'), context);
  await vm.runInContext('refresh()', context);
  assert.equal(element('#job-count').textContent, 0);
  vm.runInContext("locationPreferences = [{country:'India',city:'Pune'}]; render()", context);
  assert.equal(element('#submit-search').disabled, true);
  assert.ok(vm.runInContext('requiredErrors().join(" ")', context).includes('job designation'));
  element('#total-experience').value='0';
  vm.runInContext("designationPreferences=['Role']; render()",context);
  assert.equal(element('#submit-search').disabled, false);
  for (const [threshold, count] of [[25, 4], [50, 3], [75, 2], [100, 1]]) {
    element('#threshold').value = String(threshold);
    await vm.runInContext('runSearch()', context);
    assert.equal(element('#job-count').textContent, count);
    assert.ok(element('#export').href.startsWith(`/api/export?threshold=${threshold}&limit=5&q=&today=`));
    assert.ok(element('#job-list').innerHTML.includes('View &amp; prepare') || element('#job-list').innerHTML.includes('View & prepare'));
  }
  vm.runInContext("appliedLocations=[{country:'India',city:'Bangalore'}]; state.jobs.push({id:'bangalore',score:100,title:'Role',company:'Company',location:'Bengaluru',country:'India',matched:[],gaps:[],required:[],status:'New'}); render()", context);
  assert.equal(vm.runInContext('filtered().length',context),1,'Bangalore matches Bengaluru and excludes Pune');
  assert.equal(vm.runInContext('filtered()[0].location',context),'Bengaluru');
  assert.ok(!element('#job-list').innerHTML.includes('data-result-location="pune"'),'no hard-coded Pune tab');
  vm.runInContext("state.jobs.pop(); appliedLocations=[{country:'India',city:'Pune'}]; render()",context);
  element('#threshold').value = '25';
  vm.runInContext('render()', context);
  assert.equal(element('#job-count').textContent, 1, 'changing selection does not silently apply it');
  await vm.runInContext('runSearch(true)', context);
  assert.equal(element('#job-count').textContent, 4);
  assert.equal(feedRequests, 5);
  assert.equal(element('#search-buttons').hidden, false);
  vm.runInContext('state.resumeReady = false; render()', context);
  assert.equal(element('#search-buttons').hidden, false);
  assert.equal(element('#submit-search').disabled, true);
  assert.equal(element('#refresh-search').disabled, false);
  assert.equal(element('#connect-linkedin').disabled, true);
  assert.equal(element('#upload-confirmation').hidden, true);
  vm.runInContext('state.resumeReady = true; state.feedConfigured = false; state.jobSources = {}; state.linkedin = { name: "Candidate" }; render()', context);
  assert.equal(element('#upload-confirmation').hidden, false);
  assert.ok(element('#upload-confirmation').textContent.includes('uploaded successfully'));
  assert.equal(element('#submit-search').disabled, true, 'basic LinkedIn sign-in is not a job source');
  assert.ok(element('#submit-search').title.includes('vacancy access is not configured'));
  assert.ok(element('#search-readiness').textContent.includes('does not include vacancy access'));
  await assert.rejects(vm.runInContext('runSearch()', context), /vacancy access is not configured/);
  assert.equal(feedRequests, 5, 'an unavailable source cannot trigger a feed request');
  await vm.runInContext('runSearch(false, true)', context);
  assert.equal(element('#job-count').textContent, 4, 'optional manual JD matching remains available');
  element('#record-limit').value = '1';
  await vm.runInContext('runSearch(false, true)', context);
  assert.equal(element('#job-count').textContent, 1);
  assert.ok(element('#job-list').innerHTML.includes('Applied Job'));
  element('#record-limit').value = '0';
  await vm.runInContext('runSearch(false, true)', context);
  assert.equal(element('#job-count').textContent, 0);
  assert.ok(element('#job-list').innerHTML.includes('0 records requested'));
  element('#search').value = 'Bank';
  element('#profile-link').value = 'https://www.linkedin.com/in/example';
  await vm.runInContext('resetWorkspace()', context);
  assert.equal(cleared, true);
  assert.equal(element('#threshold').value, '75');
  assert.equal(element('#record-limit').value, '5');
  assert.equal(element('#search').value, '');
  assert.equal(element('#profile-link').value, '');
  assert.equal(element('#job-count').textContent, 0);
  assert.equal(element('#upload-confirmation').hidden, true);
  assert.equal(element('#submit-search').disabled, true);
  assert.equal(element('#refresh-search').disabled, false);
  const html = readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
  element('#sample-data').textContent = html.match(/<script id="sample-data" type="application\/json">([\s\S]*?)<\/script>/)[1];
  vm.runInContext('loadDemo()', context);
  assert.equal(element('#job-count').textContent, 0, 'loading sample data waits for Submit');
  assert.equal(element('#export').hidden, true);
  await vm.runInContext('runSearch()', context);
  assert.equal(element('#job-count').textContent, 2, 'Submit displays default sample matches');
  vm.runInContext('loadDemo()', context);
  assert.equal(element('#job-count').textContent, 0, 'reloading also waits for Submit');
  assert.equal(element('#demo-banner').hidden, false);
  assert.equal(element('#submit-search').disabled, false);
  element('#threshold').value = '50';
  await vm.runInContext('runSearch()', context);
  assert.equal(element('#job-count').textContent, 4);
  await vm.runInContext('saveDecision("demo-0", "Applied")', context);
  assert.equal(element('#job-count').textContent, 3);
  assert.equal(decisionRequests, 0, 'demo decisions never reach the real decision endpoint');
  await vm.runInContext('exitDemo()', context);
  assert.equal(element('#demo-banner').hidden, true);
  assert.equal(element('#upload-confirmation').hidden, true, 'original cleared workspace is restored');
  vm.runInContext("designationPreferences = ['Business Analyst', 'Data Analyst']; relevantExperience = {'Business Analyst':'6','Data Analyst':'2'}", context);
  element('#total-experience').value = '5';
  assert.ok(vm.runInContext('experienceErrors().join(" ")', context).includes('cannot exceed total'));
  element('#total-experience').value = '6.5';
  assert.equal(vm.runInContext('experienceErrors().length', context), 0);
  assert.equal(vm.runInContext('experienceProfile().relevantYears["Data Analyst"]', context), 2);
  element('#total-experience').value = '';
  assert.ok(vm.runInContext('experienceErrors().length', context) > 0);
});

test('search engagement shows real status, rotates tips and cleans up its timer', () => {
  const elements = new Map();
  const element = selector => {
    if (!elements.has(selector)) elements.set(selector, { hidden: true, textContent: '', scrollIntoView() {}, setAttribute(name, value) { this[name] = value; } });
    return elements.get(selector);
  };
  let tick, cleared;
  const context = vm.createContext({ applicationGuide:null, $: element, demoMode: false, setInterval(callback) { tick = callback; return 7; }, clearInterval(id) { cleared = id; } });
  const source = readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
  vm.runInContext(source.slice(source.indexOf('let searchEngagementTimer;'), source.indexOf('async function runSearch')), context);
  vm.runInContext('startSearchEngagement()', context);
  assert.equal(element('#search-engagement').hidden, false);
  assert.equal(element('#matches')['aria-busy'], 'true');
  assert.match(element('#search-progress-message').textContent, /selected job sources/);
  tick();
  assert.match(element('#search-progress-tip').textContent, /threshold/);
  vm.runInContext("setSearchPhase('Preparing your best matches', 'Loading match scores.')", context);
  assert.equal(element('#search-progress-title').textContent, 'Preparing your best matches');
  vm.runInContext('stopSearchEngagement()', context);
  assert.equal(cleared, 7);
  assert.equal(element('#search-engagement').hidden, true);
  assert.equal(element('#matches')['aria-busy'], 'false');
});
