import {randomBytes} from 'node:crypto';
import {validateProfile,profileText,suggestGroups,parseProfile} from './profile-intelligence.js';
import {scoreProfile,hardFilter} from './fit-scoring.js';
import {tailoredLines,atsCheck,resumeDocument} from './application-materials.js';
import {careerResults,runWatch,reminders,digest,stages,deliverDigest} from './career-workflow.js';
export async function careerApi(req,res,url,session,context){
 if(!url.pathname.startsWith('/api/career/'))return false;
 const {store,body,send,decisions,sessions}=context;let user=store.get(session.user);const data=req.method==='POST'?JSON.parse((await body(req,1024*1024)).toString()):{};const save=()=>store.save(session.user,user);const publicUser=()=>{const {gmailCredentials,_generation,...safe}=user;return safe;};
 const job=()=>{const found=user.jobs.find(j=>j.key===data.key||j.id===data.key)||session.jobs.find(j=>j.key===data.key||j.id===data.key)||user.pipeline.find(a=>a.key===data.key)?.job;if(!found)throw new Error('Job not found. Search or import a vacancy first.');return found;};
 if(url.pathname==='/api/career/state'&&req.method==='GET'){let expired=false;for(const draft of user.drafts){if(draft.status==='Draft'&&Date.now()-new Date(draft.createdAt)>7*86400000){draft.status='Expired';expired=true;}}if(expired)save();send(res,200,{...publicUser(),gmailConfigured:!!user.gmailCredentials,gmailAccount:user.gmailCredentials?.address||'',results:careerResults(user),reminders:reminders(user),digestPreview:digest(user),smtpConfigured:!!user.gmailCredentials||!!process.env.SMTP_HOST,tlsConfigured:!!process.env.HTTPS_CERT_FILE,storage:process.env.VERCEL?'AES-256-GCM; key held in a protected server environment variable':'AES-256-GCM; Windows key protected for the current user',skillsDue:user.profile?.skills.filter(s=>s.status==='In progress'&&s.finish<new Date().toISOString().slice(0,7))||[],defaultWatchlist:['HSBC','Barclays','NatWest','Lloyds','Deutsche Bank','Wells Fargo','American Express','EXL','Genpact']});return true;}
 if(url.pathname==='/api/career/consent'&&req.method==='POST'){if(data.agree!==true)throw new Error('Explicit consent is required.');user.consent=true;user.consentAt=new Date().toISOString();save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/export'&&req.method==='GET'){res.setHeader('Content-Disposition','attachment; filename="my-career-data.json"');send(res,200,{...publicUser(),gmailAccount:user.gmailCredentials?.address||'',note:'Authentication secrets are omitted from this export.'});return true;}
 if(url.pathname==='/api/career/delete'&&req.method==='POST'){if(data.confirm!=='DELETE')throw new Error('Type DELETE to confirm permanent erasure.');store.remove(session.user);decisions.removeUser?.(session.user);for(const s of sessions.values())if(s.user===session.user){s.jobs=[];s.resume='';s.resumeName='';delete s.linkedin;}send(res,200,{ok:true,message:'Your profile, resumes, jobs, applications and career history have been erased.'});return true;}
 if(!user.consent)throw new Error('Read and accept the data-storage notice first.');
 if(url.pathname==='/api/career/gmail'&&req.method==='POST'){if(data.save!==true||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.address)||/[\r\n]/.test(data.address)||!/^\S{16}$/.test(String(data.appPassword||'').replace(/\s/g,'')))throw new Error('Enter your Gmail address, a 16-character app password, and explicit storage consent.');user.gmailCredentials={address:data.address,appPassword:String(data.appPassword).replace(/\s/g,'')};user.settings.email=user.settings.email||data.address;user.settings.emailEnabled=false;save();send(res,200,{ok:true,message:'Gmail credentials saved encrypted. Enable digest delivery separately; no email has been sent.'});return true;}
 if(url.pathname==='/api/career/digest-send'&&req.method==='POST'){if(data.confirm!==true)throw new Error('Confirm sending this digest to the saved address.');const result=await deliverDigest(user,{force:true});send(res,200,result);return true;}
 if(url.pathname==='/api/career/profile'&&req.method==='POST'){const profile=validateProfile(data.profile);if(user.profile)user.history.push({at:new Date().toISOString(),profile:user.profile});profile.version=(user.profile?.version||0)+1;profile.sourceText=user.profile?.sourceText||session.resume;profile.confirmedAt=new Date().toISOString();user.profile=profile;user.roleGroups=data.roleGroups||user.roleGroups||suggestGroups(profile);session.resume=profileText(profile);user.resumeText=session.resume;save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/settings'&&req.method==='POST'){const settings={...user.settings,...data.settings};if(!settings.weights||['skills','domain','seniority','location','certifications'].some(k=>!Number.isFinite(Number(settings.weights[k]))||Number(settings.weights[k])<0||Number(settings.weights[k])>100))throw new Error('Provide five valid score weights between 0 and 100.');if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(settings.digestTime)||!Number.isInteger(Number(settings.followUpDays))||Number(settings.followUpDays)<1||Number(settings.followUpDays)>90)throw new Error('Choose valid reminder and digest settings.');if(settings.email&&(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(settings.email)||/[\r\n]/.test(settings.email)))throw new Error('Enter a valid digest email.');if(data.roleGroups){if(!Array.isArray(data.roleGroups)||data.roleGroups.length>20||data.roleGroups.some(g=>!g.name||!Array.isArray(g.titles)))throw new Error('Role groups need a name and title list.');user.roleGroups=data.roleGroups;}if(data.synonyms){if(!Array.isArray(data.synonyms)||data.synonyms.some(s=>!Array.isArray(s)||s.length!==2||s.some(v=>typeof v!=='string'||!v.trim())))throw new Error('Use valid synonym pairs.');user.synonyms=data.synonyms;}if(user.profile&&user.jobs[0])scoreProfile(user.profile,user.jobs[0],settings,user.synonyms);else if(Object.values(settings.weights).reduce((a,b)=>a+Number(b),0)!==100)throw new Error('Weights must total 100%.');user.settings=settings;save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/watch'&&req.method==='POST'){const health=await runWatch(user,store,session.user);session.jobs=user.jobs;send(res,200,{ok:true,health});return true;}
 if(url.pathname==='/api/career/master-resume'&&req.method==='GET'){if(!user.profile?.confirmed)throw new Error('Confirm the profile before exporting.');const format=url.searchParams.get('format');if(!['docx','pdf'].includes(format))throw new Error('Choose DOCX or PDF.');const material=tailoredLines(user.profile,{description:''});res.setHeader('Content-Disposition','attachment; filename="'+user.profile.name.replace(/[^a-z0-9_-]/gi,'_')+'_MasterResume.'+format+'"');send(res,200,await resumeDocument(material.lines,format),format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document');return true;}
 if(url.pathname==='/api/career/tailor'&&req.method==='POST'){const vacancy=job();const base=user.profile?.confirmed?user.profile:{...parseProfile(session.resume),confirmed:true};if(!session.resume)throw new Error("Upload your resume first.");const material=tailoredLines(base,vacancy);const draft={id:randomBytes(12).toString('hex'),key:vacancy.key,job:vacancy,profileVersion:user.profile?.version,createdAt:new Date().toISOString(),status:'Draft',...material,ats:atsCheck(base,vacancy),coverLetter:'',answers:{}};user.drafts.push(draft);save();send(res,200,draft);return true;}
 if(url.pathname==='/api/career/approve'&&req.method==='POST'){const draft=user.drafts.find(d=>d.id===data.id);if(!draft||data.approve!==true)throw new Error('Review and explicitly approve the application package.');if(Date.now()-new Date(draft.createdAt)>7*86400000){draft.status='Expired';save();throw new Error('Draft expired; generate and review a new version.');}if(draft.profileVersion!==user.profile?.version)throw new Error('Profile changed; generate a fresh draft.');if(data.text!==undefined){if(typeof data.text!=='string'||data.text.trim().length<40||data.text.length>100000)throw new Error('Review a complete resume before approval.');draft.tailored=data.text.trim();draft.lines=draft.tailored.split(/\n/);draft.userEdited=true;}draft.status='Approved';draft.approvedAt=new Date().toISOString();let application=user.pipeline.find(a=>a.key===draft.key);if(!application){application={key:draft.key,job:draft.job,stage:'Saved',updatedAt:draft.approvedAt,history:[{from:null,to:'Saved',at:draft.approvedAt}]};user.pipeline.push(application);}application.resumeVersion=draft.id;save();send(res,200,{ok:true,url:draft.job.applyLink,message:'Package approved. Submit manually on the employer website; nothing has been sent by this app.'});return true;}
 if(url.pathname==='/api/career/resume'&&req.method==='GET'){const draft=user.drafts.find(d=>d.id===url.searchParams.get('id'));if(!draft||draft.status!=='Approved')throw new Error('Approve this version before exporting.');const format=url.searchParams.get('format');if(!['docx','pdf'].includes(format))throw new Error('Choose DOCX or PDF.');const name=[user.profile?.name||"Candidate",draft.job.company,draft.job.title].map(s=>String(s).replace(/[^a-z0-9_-]/gi,'_').slice(0,60)).join('_')+'.'+format;res.setHeader('Content-Disposition','attachment; filename="'+name+'"');send(res,200,await resumeDocument(draft.lines,format),format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document');return true;}
 if(url.pathname==='/api/career/stage'&&req.method==='POST'){if(!stages.includes(data.stage))throw new Error('Choose a valid pipeline stage.');const vacancy=job();let entry=user.pipeline.find(a=>a.key===vacancy.key);if(!entry){entry={key:vacancy.key,job:vacancy,history:[],resumeVersion:user.profile?.version};user.pipeline.push(entry);}if(entry.stage!==data.stage)entry.history.push({from:entry.stage||null,to:data.stage,at:new Date().toISOString()});entry.resumeVersion=[...user.drafts].reverse().find(d=>d.key===vacancy.key&&d.status==='Approved')?.id||entry.resumeVersion;if(entry.stage!==data.stage)entry.updatedAt=new Date().toISOString();entry.stage=data.stage;user.decisions[vacancy.key]={status:data.stage,updatedAt:entry.updatedAt};if(data.stage==='Applied')decisions.set(session.user,vacancy.key,'Applied');save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/snooze'&&req.method==='POST'){const entry=user.pipeline.find(a=>a.key===data.key);if(!entry)throw new Error('Application not found');entry.snoozeUntil=new Date(Date.now()+3*86400000).toISOString();save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/split'&&req.method==='POST'){user.splitKeys=[...new Set([...(user.splitKeys||[]),...(data.keys||[])])];save();send(res,200,{ok:true});return true;}
 if(url.pathname==='/api/career/pipeline-export'&&req.method==='GET'){const quote=s=>'"'+String(s||'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';res.setHeader('Content-Disposition','attachment; filename="application-pipeline.csv"');send(res,200,[['Job','Company','Source','Stage','Updated','Fit score','Resume version'],...user.pipeline.map(a=>[a.job.title,a.job.company,a.job.source,a.stage,a.updatedAt,user.profile?scoreProfile(user.profile,a.job,user.settings,user.synonyms).score:'',a.resumeVersion])].map(row=>row.map(quote).join(',')).join('\r\n'),'text/csv');return true;}
 throw new Error('Career operation not found.');
}
