import {matchJob,extractSkills} from './matching.js';
import {profileText} from './profile-intelligence.js';
export const scoreVersion='fit-1.0';
export const defaultSynonyms=[['Teradata','SQL'],['Teradata','Data warehouse'],['CRA reporting','Credit bureau reporting'],['S2T mapping','Source-to-target mapping']];
const domain=['Regulatory Reporting','Credit Risk','Banking','Basel','IFRS 9','Credit bureau reporting','Source-to-target mapping','Data Governance','Data Lineage','CCDS','Collections','Recoveries'];
const normal=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const contains=(text,term)=>(' '+normal(text)+' ').includes(' '+normal(term)+' ');
export function scoreProfile(profile,job,settings={},synonyms=[]){
 const text=profileText(profile),jd=job.description||'',pairs=[...defaultSynonyms,...synonyms];const lines=text.split('\n');
 const requirementNames=[...new Set([...extractSkills(jd),...domain.filter(d=>contains(jd,d)),...pairs.flat().filter(d=>contains(jd,d)),...profile.skills.filter(s=>contains(jd,s.name)).map(s=>s.name)])];
 const reasons=requirementNames.map(name=>{const own=profile.skills.find(s=>normal(s.name)===normal(name)||pairs.some(([a,b])=>(normal(a)===normal(name)&&normal(b)===normal(s.name))||(normal(b)===normal(name)&&normal(a)===normal(s.name))));const evidence=lines.find(l=>contains(l,name));const synonym=pairs.find(([a,b])=>(normal(b)===normal(name)&&lines.some(l=>contains(l,a)))||(normal(a)===normal(name)&&lines.some(l=>contains(l,b))));const synonymLine=synonym&&lines.find(l=>contains(l,synonym[0])||contains(l,synonym[1]));return {name,status:own?.status==='In progress'?'near-fit':evidence||synonym?'matched':'missing',evidence:evidence||synonymLine||'',viaSynonym:!!synonym&&!evidence,readyBy:own?.finish||''};});
 const proficient=reasons.filter(r=>r.status==='matched'),near=reasons.filter(r=>r.status==='near-fit');const domainReq=domain.filter(d=>contains(jd,d));const domainMatches=domainReq.filter(d=>proficient.some(r=>normal(r.name)===normal(d)));
 const requiredYears=job.experienceMin||Number(jd.match(/(\d{1,2})\s*(?:\+|[-–]\s*\d{1,2})?\s*(?:years|yrs)\s*(?:of\s*)?(?:relevant\s*|professional\s*)?experience/i)?.[1]);
 const certReq=[...profile.certifications,...profile.skills.filter(s=>s.status==='Certified').map(s=>s.name)].filter(c=>contains(jd,c));const desired=profile.preferences?.locations||[];const canon=s=>normal(s).replace(/gurgaon/g,'gurugram').replace(/bangalore/g,'bengaluru');
 const parts={skills:{score:reasons.length?100*(proficient.length+near.length*.5)/reasons.length:0,reason:`${proficient.length} proven, ${near.length} in progress, ${reasons.length} recognised requirements`},domain:{score:domainReq.length?100*domainMatches.length/domainReq.length:0,reason:domainReq.length?`${domainMatches.length}/${domainReq.length} recognised domain terms`:'Domain requirements unknown'},seniority:{score:requiredYears?Math.min(100,100*Number(profile.totalYears||0)/requiredYears):0,reason:requiredYears?`${requiredYears} years requested; ${profile.totalYears||0} confirmed`:'Experience requirement unknown'},location:{score:desired.some(p=>canon(job.location).includes(canon(p.city)))?100:desired.length?0:50,reason:desired.length?'Compared with confirmed preferred cities':'No confirmed city preference'},certifications:{score:certReq.length?100:0,reason:certReq.length?certReq.join(', '):'No confirmed certification requirement detected'}};
 const weights=settings.weights||{skills:40,domain:25,seniority:15,location:10,certifications:10};const total=Object.values(weights).reduce((a,b)=>a+Number(b),0);if(total!==100||Object.values(weights).some(w=>!Number.isFinite(Number(w))||Number(w)<0))throw new Error('Score weights must total 100%.');
 const score=Math.round(Object.entries(parts).reduce((sum,[key,part])=>sum+part.score*Number(weights[key])/100,0));const legacy=matchJob(text,job);
 return {...legacy,score,matched:proficient.map(r=>r.name),gaps:reasons.filter(r=>r.status==='missing').map(r=>r.name),nearFit:near,requirements:reasons,scoreParts:parts,scoreWeights:weights,required:reasons.map(r=>r.name),scoreVersion,profileVersion:profile.version,scoredAt:new Date().toISOString()};
}
export function hardFilter(job,profile,settings){const f=settings.hardFilters||{},reasons=[];const work=(job.workMode||'').toLowerCase();if(f.workModes?.length&&!f.workModes.map(s=>s.toLowerCase()).includes(work))reasons.push('Work mode does not meet filter or is unknown');if(f.minExperience&&(!job.experienceMin||job.experienceMin<Number(f.minExperience)))reasons.push('Advertised experience band below filter or unknown');if(f.minSalary&&typeof job.salaryMax==='number'&&job.salaryMax<Number(f.minSalary))reasons.push('Salary below minimum');if(f.companyTypes?.length&&!f.companyTypes.includes(job.companyType))reasons.push('Company type does not meet filter or is unknown');if(f.noticeDays&&job.noticeDays&&Number(profile.noticeDays)>Number(job.noticeDays))reasons.push('Notice period exceeds employer limit');return {hidden:reasons.length>0,reasons,salaryUnknown:!!f.minSalary&&job.salaryMax==null};}
export function mergePostings(jobs,splitKeys=[]){const city=location=>{const raw=normal(location).replace(/gurgaon/g,'gurugram').replace(/bangalore/g,'bengaluru');return ['pune','delhi','gurugram','noida','bengaluru','hyderabad','mumbai','chennai'].find(c=>raw.includes(c))||raw;};const result=[];const similarity=(a,b)=>{const x=new Set(normal(a).split(' ')),y=new Set(normal(b).split(' '));return 2*[...x].filter(v=>y.has(v)).length/(x.size+y.size||1);};for(const job of jobs){const existing=result.find(j=>!splitKeys.includes(job.key)&&!splitKeys.includes(j.key)&&normal(j.company)===normal(job.company)&&city(j.location)===city(job.location)&&similarity(j.title,job.title)>=.9&&Math.abs(new Date(j.posted)-new Date(job.posted))<=14*86400000);if(existing){existing.sourceLinks=[...(existing.sourceLinks||[{url:existing.applyLink,source:existing.source,key:existing.key}]),{url:job.applyLink,source:job.source,key:job.key}];existing.mergedKeys=[...(existing.mergedKeys||[existing.key]),job.key];}else result.push({...job});}return result;}
